# btrfs-scrub
# Autogenerated from man page /usr/share/man/man8/btrfs-scrub.8.gz
complete -c btrfs-scrub -s c -d and
complete -c btrfs-scrub -s n -d options
complete -c btrfs-scrub -s B
complete -c btrfs-scrub -s d
complete -c btrfs-scrub -s q
complete -c btrfs-scrub -s r
complete -c btrfs-scrub -s R
complete -c btrfs-scrub -s f

