# btrfs-send
# Autogenerated from man page /usr/share/man/man8/btrfs-send.8.gz
complete -c btrfs-send -s e
complete -c btrfs-send -s p
complete -c btrfs-send -s c
complete -c btrfs-send -s f
complete -c btrfs-send -l no-data
complete -c btrfs-send -s v -l verbose
complete -c btrfs-send -s q -l quiet

