# devio
# Autogenerated from man page /usr/share/man/man1/devio.1.gz
complete -c devio -s h -l help -d 'Show summary of options'
complete -c devio -s v -l version -d 'Show version of program.  SEE ALSO dd (1), cat (1)'

