# dtc
# Autogenerated from man page /usr/share/man/man1/dtc.1.gz
complete -c dtc -s h -d 'Display help text'
complete -c dtc -s q -d Quiet:
complete -c dtc -s v -d 'Print DTC version and exit'
complete -c dtc -o qq
complete -c dtc -o qqq
complete -c dtc -s I -d 'Input formats are: dts - device tree source text'
complete -c dtc -s o -d 'Dump the result into a file, instead of stdout'
complete -c dtc -s O -d 'Output formats are: dts - device tree source text'
complete -c dtc -s V -d 'Blob version to produce'
complete -c dtc -s d
complete -c dtc -s R -d 'Make space for <number> reserve map entries (only relevant for dtb and asm ou…'
complete -c dtc -s S -d 'Make the blob at least <bytes> long (extra space)'
complete -c dtc -s p -d 'Add padding to the blob of <bytes> long (extra space)'
complete -c dtc -s b -d 'Set the physical boot CPU'
complete -c dtc -s f -d 'Force - try to produce output even if the input tree has errors'
complete -c dtc -s s -d 'Sort nodes and properties before outputting (only useful for comparing trees)'
complete -c dtc -s H -d 'phandle formats are: legacy - "linux,phandle" properties only'

