# fdtput
# Autogenerated from man page /usr/share/man/man1/fdtput.1.gz
complete -c fdtput -s h -d 'Print this help'
complete -c fdtput -s v -d 'Verbose: display each value decoded from command line'
complete -c fdtput -s t -d 'Type of data'

