# kwboot
# Autogenerated from man page /usr/share/man/man1/kwboot.1.gz
complete -c kwboot -s b -d 'Handshake; then upload file image over TTY'
complete -c kwboot -s p -d 'In combination with -b, patches the header in image prior to upload, to "UART…'
complete -c kwboot -s t -d 'Run a terminal program, connecting standard input and output to . RB TTY'

