# thin_restore
# Autogenerated from man page /usr/share/man/man8/thin_restore.8.gz
complete -c thin_restore -s h -l help -d 'Print help and exit'
complete -c thin_restore -s V -l version -d 'Print version information and exit'
complete -c thin_restore -s q -l quiet -d 'Suppress output messages, return only exit code'
complete -c thin_restore -s i -l input -d 'Input file containing XML metadata'
complete -c thin_restore -s o -l output -d 'Output file or device for restored binary metadata'

